### PR TITLE
Add .bash_history to .gitignore

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by andrey-yantsen** [comment]
Hm... unexpected way to break macos tests :D Thanks!

By the way, can you please tell me the story about how you've ended up with .bash_history in `plex-stub-data/config/`?

**Comment by glensc** [comment]
simple, I entered the container with bash: `docker exec plex bash`

**Comment by andrey-yantsen** [comment]
Ah, simple indeed. Normally I'm creating containers with a copy of the `plex-stub-data`, not mounting the original one to the container.

**Comment by glensc** [comment]
@andrey-yantsen I just used your container to launch plex instance with test your data, expected it to go smoothly. but somewhy the PMS gave an "internal error", so I entered the co0ntainer to see the logs.

as for the problem, I don't know what was it, it just went away at some point. i.e I could not tie the error to any of my specific activity.

ps: I don't use this library at all.

**Comment by glensc** [comment]
and it's due to plex container `HOME=/config`, so there may appear more junk. perhaps better be invert to that exclude everything, and then include only wanted content:

```
*
!/wanted1
!/wanted2
```

or, don't overmount `/config`, but specific a dir instead, `/config/Library` for example

**Pull request merged**
