### PR TITLE
fix!: Profile de-serialization when using new subtitle setting options

### PR DESCRIPTION
**Pull request by dsander**
BREAKING CHANGE: `Profile#default_subtitle_accessibility` is now an `Enum`
BREAKING CHANGE: `Profile#default_subtitle_forced` is now an `Enum`.

In the current MyPlex account settings both `default_subtitle_accessibility` and `default_subtitle_forced` offer more than two options and thus can not be represented as a boolean.

The current values and names for the enum variants have been taken from the settings HTML.

```
<select id="defaultSubtitleAccessibility" name="defaultSubtitleAccessibility">
   <option value="0">Prefer non-SDH subtitles</option>
   <option value="1">Prefer SDH subtitles</option>
   <option value="2">Only show SDH subtitles</option>
   <option value="3">Only show non-SDH subtitles</option>
</select>
```
```
<select id="defaultSubtitleForced" name="defaultSubtitleForced">
   <option value="0">Prefer non-forced subtitles</option>
   <option value="1">Prefer forced subtitles</option>
   <option value="2">Only show forced subtitles</option>
   <option value="3">Only show non-forced subtitles</option>
</select>
```

### CODE REVIEW

**Comment by andrey-yantsen** [comment]
It doesn't look like it's related to Plex v1.32 since it comes from MyPlex. I wonder how they keep compatibility with the older versions in that case :)

What do you think about making these fields Enums instead of u8-s?

**Comment by andrey-yantsen** [comment]
Oh wait, you're not Dave! I didn't expect to see anybody new :D

Thank you, Dominik!

**Comment by andrey-yantsen** [comment]
Also, would you mind rewriting the commit message in the [conventional commits](https://conventionalcommits.org) format?

**Comment by dsander** [comment]
Hi there Andrew! 👋 

> It doesn't look like it's related to Plex v1.32 since it comes from MyPlex. I wonder how they keep compatibility with the older versions in that case :)

Ah, that makes sense. Maybe the older clients are just falling back to the previous default?

> What do you think about making these fields Enums instead of u8-s?

Thought about it and can do it if you prefer it. I went with the simple change also because it should be forwards compatible as long as Plex keeps the value a (not too big) integer. An enum would of course be more descriptive. 😄 

> Also, would you mind rewriting the commit message in the [conventional commits](https://conventionalcommits.org/) format?

Sure, no problem.

**Comment by andrey-yantsen** [comment]
> Thought about it and can do it if you prefer it. I went with the simple change also because it should be forwards compatible as long as Plex keeps the value a (not too big) integer. An enum would of course be more descriptive. 😄

I'd prefer having an enum here. I think those options have existed for quite a while now, — I remember changing them in the account's settings about 4 years ago. I guess I just didn't connect the dots between the UI and the code 🤦‍♂️ At this stage, I don't see many usages for the library, where the end developer will need to match those enums, so it shouldn't be a big inconvenience for most.

**Comment by dsander** [comment]
> I'd prefer having an enum here. 

Sounds good to me. Should I make the de-serializer fail if it Plex ever adds a new value or return something like `DefaultSubtitleAccessibility::Unknown(4)`?

**Comment by andrey-yantsen** [comment]
Just do the same thing as in all the other serde-backed enums (e.g. [AutoSelectSubtitleMode](https://github.com/andrey-yantsen/plex-api.rs/blob/49111f1ca1f03b9390d7c4a245c97bfd8fe30efc/crates/plex-api/src/myplex/account.rs#L35-L44)). This way, a new value won't break the code using the library, but we might notice the issue in the tests.

**Review by andrey-yantsen — DISMISSED** [review]
Thanks again, Dominik! Looks great.

Please don't hesitate to pop by if you'll find anything else :)

**Comment by andrey-yantsen** [comment]
Ouch, I should've waited for the checks to finish 🤣 Oh, that cruel Clippy.

Would you mind either changing the variants' names or just adding `#[allow(clippy::enum_variant_names)]` (or whatever will disable that check)?

**Comment by dsander** [comment]
> Ouch, I should've waited for the checks to finish 🤣 Oh, that cruel Clippy.

Hah! No worries, I thought that clippy was part of the pre commit hook, but that must have seen something else 😄 

Thanks for the feedback!

**Comment by andrey-yantsen** [comment]
It should be executed as a pre-commit hook, but looks like something went wrong this time 🤷‍♂️

Thanks again!

**Pull request merged**
